<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.ferry</groupId>
	<artifactId>qlaundry</artifactId>
	<version>1.0.0</version>
	<name>qlaundry</name>
	<modules>
		<module>user-service/user-core</module>
		<module>user-service/user-domain</module>
		<module>utils/identity-generator</module>
		<module>utils/cache-tools</module>
		<module>utils/token-manager</module>
		<module>utils/internal-commons</module>
		<module>utils/json-tools</module>
	</modules>
	<packaging>pom</packaging>
	<description>qlaundry</description>

	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>

	<properties>
		<java.version>25</java.version>
		<maven.compiler.source>25</maven.compiler.source>
		<maven.compiler.target>25</maven.compiler.target>
		<spring-boot.version>4.1.0</spring-boot.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>
