# Made by [MR Ferry™] on September 2026
services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: qlaundry_analytics
      CLICKHOUSE_USER: analytics
      CLICKHOUSE_PASSWORD: "12345"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./analytics-gateway/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse-data:
