<?xml version="1.0" encoding="UTF-8"?>
<!--~~~~~~~~~~~~~~~~~~~~~
  ~ Made by [MR Ferry™] ~
  ~ on September 2026   ~
  ~~~~~~~~~~~~~~~~~~~~~-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.ferry</groupId>
		<artifactId>qlaundry</artifactId>
		<version>1.0.0</version>
		<relativePath/>
	</parent>
	<artifactId>analytics-gateway</artifactId>
	<name>analytics-gateway</name>
	<description>analytics-gateway</description>
	<properties>
		<java.version>25</java.version>
		<clickhouse-client.version>0.9.8</clickhouse-client.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.ferry</groupId>
			<artifactId>analytics-domain</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.ferry</groupId>
			<artifactId>analytics-core</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.ferry</groupId>
			<artifactId>json-tools</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.clickhouse</groupId>
			<artifactId>client-v2</artifactId>
			<version>${clickhouse-client.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<executions>
					<execution>
						<id>default-compile</id>
						<phase>compile</phase>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<annotationProcessorPaths>
								<path>
									<groupId>org.projectlombok</groupId>
									<artifactId>lombok</artifactId>
								</path>
							</annotationProcessorPaths>
						</configuration>
					</execution>
					<execution>
						<id>default-testCompile</id>
						<phase>test-compile</phase>
						<goals>
							<goal>testCompile</goal>
						</goals>
						<configuration>
							<annotationProcessorPaths>
								<path>
									<groupId>org.projectlombok</groupId>
									<artifactId>lombok</artifactId>
								</path>
							</annotationProcessorPaths>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
