/************************
 * Made by [MR Ferry™]  *
 * on Juli 2026         *
 ************************/

import type {Order} from '../domain/Order';
import type {LaundryService} from '../domain/Service';

export const fallbackServices: LaundryService[] = [
	{
		id: 'wash-fold',
		name: 'Wash & Fold',
		description: 'Freshly washed, dried and neatly folded. Perfect for everyday laundry.',
		pricePerUnit: 8000,
		unit: 'kg',
		estimatedHours: 24,
		expressMultiplier: 1.5,
		popular: true,
		active: true,
		category: 'wash',
	},
	{
		id: 'wash-iron',
		name: 'Wash & Iron',
		description: 'Complete clean with a crisp, professional press. Great for workwear.',
		pricePerUnit: 12000,
		unit: 'kg',
		estimatedHours: 48,
		expressMultiplier: 1.5,
		popular: true,
		active: true,
		category: 'wash',
	},
	{
		id: 'dry-clean',
		name: 'Dry Cleaning',
		description: 'Gentle solvent-based care for suits, dresses and delicate fabrics.',
		pricePerUnit: 35000,
		unit: 'item',
		estimatedHours: 72,
		expressMultiplier: 2.0,
		popular: false,
		active: true,
		category: 'dry_clean',
	},
	{
		id: 'iron-only',
		name: 'Iron Only',
		description: 'Professional pressing for an already-clean wardrobe.',
		pricePerUnit: 5000,
		unit: 'item',
		estimatedHours: 12,
		expressMultiplier: 1.5,
		popular: false,
		active: true,
		category: 'iron',
	},
	{
		id: 'bed-linen',
		name: 'Bed Linen',
		description: 'Full wash and fold for sheets, duvet covers, pillow cases and more.',
		pricePerUnit: 45000,
		unit: 'set',
		estimatedHours: 48,
		expressMultiplier: 1.5,
		popular: false,
		active: true,
		category: 'specialty',
	},
	{
		id: 'sneaker-clean',
		name: 'Sneaker Cleaning',
		description: 'Deep clean and refresh for your favourite sneakers and shoes.',
		pricePerUnit: 50000,
		unit: 'item',
		estimatedHours: 72,
		expressMultiplier: 2.0,
		popular: true,
		active: true,
		category: 'specialty',
	},
];

export const fallbackOrders: Order[] = [
	{
		id: 'ord-001',
		orderNumber: 'QL-1031',
		customerId: 'cust-001',
		customerName: 'Budi Santoso',
		customerPhone: '081234567890',
		customerAddress: 'Jl. Mawar No. 12, Kelapa Gading, Jakarta Utara',
		serviceId: 'wash-fold',
		serviceName: 'Wash & Fold',
		items: [
			{type: 'shirt', label: 'Shirt / Blouse', quantity: 5},
			{type: 'pants', label: 'Pants / Shorts', quantity: 3},
		],
		quantity: 4,
		weightKg: 4.2,
		subtotal: 33600,
		discount: 0,
		totalPrice: 33600,
		priority: 'normal',
		paymentMethod: 'transfer',
		paymentStatus: 'paid',
		status: 'completed',
		notes: '',
		createdAt: '2026-07-10T08:00:00Z',
		pickupDate: '2026-07-10',
		estimatedDelivery: '2026-07-11',
		completedAt: '2026-07-11T14:00:00Z',
	},
	{
		id: 'ord-002',
		orderNumber: 'QL-1032',
		customerId: 'cust-002',
		customerName: 'Siti Rahayu',
		customerPhone: '082345678901',
		customerAddress: 'Jl. Melati No. 7, Tebet, Jakarta Selatan',
		serviceId: 'wash-iron',
		serviceName: 'Wash & Iron',
		items: [
			{type: 'shirt', label: 'Shirt / Blouse', quantity: 4},
			{type: 'dress', label: 'Dress / Skirt', quantity: 2},
		],
		quantity: 6,
		weightKg: 3.8,
		subtotal: 45600,
		discount: 0,
		totalPrice: 45600,
		priority: 'normal',
		paymentMethod: 'cash',
		paymentStatus: 'paid',
		status: 'in_progress',
		notes: 'Pisahkan pakaian putih',
		createdAt: '2026-07-12T09:30:00Z',
		pickupDate: '2026-07-12',
		estimatedDelivery: '2026-07-14',
	},
	{
		id: 'ord-003',
		orderNumber: 'QL-1033',
		customerId: 'cust-003',
		customerName: 'Ahmad Kurniawan',
		customerPhone: '083456789012',
		customerAddress: 'Jl. Kenanga No. 45, Menteng, Jakarta Pusat',
		serviceId: 'dry-clean',
		serviceName: 'Dry Cleaning',
		items: [
			{type: 'jacket', label: 'Jacket / Coat', quantity: 2},
			{type: 'dress', label: 'Dress / Skirt', quantity: 1},
		],
		quantity: 3,
		subtotal: 105000,
		discount: 0,
		totalPrice: 105000,
		priority: 'normal',
		paymentMethod: 'qris',
		paymentStatus: 'paid',
		status: 'pending',
		notes: 'Hati-hati bahan sutra pada gaun',
		createdAt: '2026-07-13T10:15:00Z',
		pickupDate: '2026-07-14',
		estimatedDelivery: '2026-07-17',
	},
	{
		id: 'ord-004',
		orderNumber: 'QL-1034',
		customerId: 'cust-001',
		customerName: 'Budi Santoso',
		customerPhone: '081234567890',
		customerAddress: 'Jl. Mawar No. 12, Kelapa Gading, Jakarta Utara',
		serviceId: 'wash-iron',
		serviceName: 'Wash & Iron',
		items: [
			{type: 'uniform', label: 'Uniform', quantity: 5},
		],
		quantity: 5,
		weightKg: 3.2,
		subtotal: 57600,
		discount: 5760,
		totalPrice: 51840,
		promoCode: 'LOYAL10',
		priority: 'express',
		paymentMethod: 'transfer',
		paymentStatus: 'unpaid',
		status: 'confirmed',
		notes: 'Seragam kantor, perlu rapi',
		createdAt: '2026-07-13T14:00:00Z',
		pickupDate: '2026-07-14',
		estimatedDelivery: '2026-07-15',
	},
	{
		id: 'ord-005',
		orderNumber: 'QL-1035',
		customerId: 'cust-004',
		customerName: 'Dewi Kusuma',
		customerPhone: '084567890123',
		customerAddress: 'Jl. Anggrek No. 22, Kebayoran Baru, Jakarta Selatan',
		serviceId: 'bed-linen',
		serviceName: 'Bed Linen',
		items: [
			{type: 'bed_linen', label: 'Bed Linen', quantity: 2},
		],
		quantity: 2,
		subtotal: 90000,
		discount: 0,
		totalPrice: 90000,
		priority: 'normal',
		paymentMethod: 'transfer',
		paymentStatus: 'paid',
		status: 'ready',
		notes: '',
		createdAt: '2026-07-11T11:00:00Z',
		pickupDate: '2026-07-11',
		estimatedDelivery: '2026-07-13',
	},
	{
		id: 'ord-006',
		orderNumber: 'QL-1036',
		customerId: 'cust-005',
		customerName: 'Reza Firmansyah',
		customerPhone: '085678901234',
		customerAddress: 'Jl. Dahlia No. 8, Cempaka Putih, Jakarta Pusat',
		serviceId: 'sneaker-clean',
		serviceName: 'Sneaker Cleaning',
		items: [
			{type: 'other', label: 'Other', quantity: 2},
		],
		quantity: 2,
		subtotal: 100000,
		discount: 0,
		totalPrice: 100000,
		priority: 'express',
		paymentMethod: 'qris',
		paymentStatus: 'paid',
		status: 'out_for_delivery',
		notes: 'Nike Air Max dan Adidas Ultraboost',
		createdAt: '2026-07-13T08:30:00Z',
		pickupDate: '2026-07-13',
		estimatedDelivery: '2026-07-14',
	},
	{
		id: 'ord-007',
		orderNumber: 'QL-1037',
		customerId: 'cust-002',
		customerName: 'Siti Rahayu',
		customerPhone: '082345678901',
		customerAddress: 'Jl. Melati No. 7, Tebet, Jakarta Selatan',
		serviceId: 'iron-only',
		serviceName: 'Iron Only',
		items: [
			{type: 'shirt', label: 'Shirt / Blouse', quantity: 8},
			{type: 'pants', label: 'Pants / Shorts', quantity: 4},
		],
		quantity: 12,
		subtotal: 60000,
		discount: 0,
		totalPrice: 60000,
		priority: 'normal',
		paymentMethod: 'cash',
		paymentStatus: 'unpaid',
		status: 'picked_up',
		notes: '',
		createdAt: '2026-07-14T07:00:00Z',
		pickupDate: '2026-07-14',
		estimatedDelivery: '2026-07-14',
	},
	{
		id: 'ord-008',
		orderNumber: 'QL-1038',
		customerId: 'cust-006',
		customerName: 'Indah Permata',
		customerPhone: '086789012345',
		customerAddress: 'Jl. Flamboyan No. 3, Pisangan, Jakarta Timur',
		serviceId: 'wash-fold',
		serviceName: 'Wash & Fold',
		items: [
			{type: 'shirt', label: 'Shirt / Blouse', quantity: 6},
			{type: 'towel', label: 'Towel', quantity: 4},
		],
		quantity: 5,
		weightKg: 5.1,
		subtotal: 40800,
		discount: 0,
		totalPrice: 40800,
		priority: 'normal',
		paymentMethod: 'transfer',
		paymentStatus: 'paid',
		status: 'completed',
		notes: '',
		createdAt: '2026-07-09T13:00:00Z',
		pickupDate: '2026-07-09',
		estimatedDelivery: '2026-07-10',
		completedAt: '2026-07-10T10:00:00Z',
	},
	{
		id: 'ord-009',
		orderNumber: 'QL-1039',
		customerId: 'cust-003',
		customerName: 'Ahmad Kurniawan',
		customerPhone: '083456789012',
		customerAddress: 'Jl. Kenanga No. 45, Menteng, Jakarta Pusat',
		serviceId: 'wash-iron',
		serviceName: 'Wash & Iron',
		items: [
			{type: 'shirt', label: 'Shirt / Blouse', quantity: 10},
			{type: 'pants', label: 'Pants / Shorts', quantity: 5},
			{type: 'jacket', label: 'Jacket / Coat', quantity: 1},
		],
		quantity: 16,
		weightKg: 6.5,
		subtotal: 78000,
		discount: 7800,
		totalPrice: 70200,
		promoCode: 'NEWUSER',
		priority: 'normal',
		paymentMethod: 'qris',
		paymentStatus: 'paid',
		status: 'cancelled',
		notes: 'Dibatalkan karena pindah jadwal',
		createdAt: '2026-07-08T09:00:00Z',
		pickupDate: '2026-07-08',
		estimatedDelivery: '2026-07-10',
	},
	{
		id: 'ord-010',
		orderNumber: 'QL-1040',
		customerId: 'cust-007',
		customerName: 'Hendra Wijaya',
		customerPhone: '087890123456',
		customerAddress: 'Jl. Cempaka No. 17, Gambir, Jakarta Pusat',
		serviceId: 'wash-fold',
		serviceName: 'Wash & Fold',
		items: [
			{type: 'shirt', label: 'Shirt / Blouse', quantity: 12},
			{type: 'pants', label: 'Pants / Shorts', quantity: 6},
			{type: 'towel', label: 'Towel', quantity: 3},
		],
		quantity: 8,
		weightKg: 7.8,
		subtotal: 62400,
		discount: 0,
		totalPrice: 62400,
		priority: 'normal',
		paymentMethod: 'transfer',
		paymentStatus: 'paid',
		status: 'in_progress',
		notes: '',
		createdAt: '2026-07-14T06:00:00Z',
		pickupDate: '2026-07-14',
		estimatedDelivery: '2026-07-15',
	},
];
