spring:
  application:
    name: user-web-service
  datasource:
    url: jdbc:postgresql://localhost:5432/qlaundry?currentSchema=users
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      password: '12345'
  threads:
    virtual:
      enabled: true

server:
  port: 8101

app:
  notification:
    stream:
      email:
        key: 'notification:email:'
  token:
    private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNgNUjP15kfhj92bHRBly29FON8YeKn8IWyo+hSMYjMBoUEMO1eWUvgwPjNRdQrV+qCEjJap1SBpyAQAckMVRNo/mgs+5WS5R0L6DyjukYXs3xLjhd8pPPz0s16RhnvoqPnuYFlCCndRnI/MVCm3/43/Leezf4Ml5wwSxY2K342VL+BUUTKlptUCrCXk6yat9g6ehwsvdpkVsoYzo4nuyRELHDfMubvt6mli1qD+o1fxqR2OJhbidJdXp3XRgAsaftvl/98pTIPCzRFWxugwOaVZsB+od2sWi6FXash9QPUx9Vku1GxmSvDCFlTK9d3pZVOvOT4DsotXIr+WJskzfBAgMBAAECggEAIShAe3jt09INWeaw4ZR2C3udgEwFqLtrzKiZ3Gs1CO1pxRi1XcenU1n/cRPvs0UzUmhsHLohMGBqX5O1He+q9gIB33ODU5TLRaR/rVNF+c17dga/8oHsESjAWQOckUn1lQRi1xNA4jQAg+TWNmUyPzzHCi2gaLabyp6TIgddU/FWSZHIVNf1a05jB2IqPz1HZeQBiGrkQiEoUAYiPNK6/Un1h1Z9T8VkfF4PJ3JsBCPkx/5kLiAkosNbGka9bUmxEXotfoTk5eGqQgXsXErEA0ORhFlH0feuNEeFV0vZlOMNB823OebME51DCX/Z3zUFqO9IbVqYys5SsW6WM1HmZwKBgQDOpSHm5veGlVdQw7CtWXTN/DrHG1v2j4Naur7qjhOjDHiuiTC0UplYrIneDVK9MH6dQe3SP7Z8Q9MeqLBkQkCcDZZhuDdfj0wSBJVAZ0wX88kdwNKGpImf+rFj4a9njLYnA7+bAGb8y9R4i/sayT6a0p0Zt3yFjJ0Qr4pVC48kywKBgQD+leMwTclvbS265Qf7j2N5MHg4SUbtfcrpzLlCMcP2kfaFQp3v5+495b84ko5LUBAggpbouLcSlyPlrgTrEi9ZHg0Sjjj8D2JQ1byFqhFX5HzrZUhLkTEpT1mTUseVs6SmjM6akB2Ye6zmj9HqmNst0tVncgbL0hjFsFt7vw2QIwKBgAZg9I3zHTrrSzm0ALUpKMDfA1V4E7ulrHFViGUnI5YJ4YPJulYmopMpKExRbvdmEtJ54YR28QQe99pfbKp7nRD0Hms/y33Ip5l6yLynM6MdpFylwhnj5Feq3mTt54Mzxb+ojvaS6ZruE83wzDyEb8lJrQ3JKy/YKlUEhimf5LhHAoGAdR7zo9dFYnOx5BdVss9mjexUgmCDtuJ2JVU/rUpDwv2nkerxydrDacp2TEpwGAm/QZWSY4IHBxBtPU7viE2XZsJCdVTktmFFc7bAwiVZUTwWlBzGQ62KFl0g8nvUwfQhPVXt/oFqfCn5gyCLDAhCXTRvZOW6Zq5DIz9c9vMQBE0CgYEAk/5kpCQBAbikyunQnNktz1vbtlIRddgJ3KdKgBli+a05DWZ3n+sZy2CjXQYeaOO9h5P1u+AMfPamXlwnAmCZDQ3hU908dv826Jw9+dA4k1mI2axKr6HmJui/epSwhXv1Kb2DGVb4r4q+sp3HgtOIFjMgKJpV8OsqrSt5JZrXApY="
    public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzYDVIz9eZH4Y/dmx0QZctvRTjfGHip/CFsqPoUjGIzAaFBDDtXllL4MD4zUXUK1fqghIyWqdUgacgEAHJDFUTaP5oLPuVkuUdC+g8o7pGF7N8S44XfKTz89LNekYZ76Kj57mBZQgp3UZyPzFQpt/+N/y3ns3+DJecMEsWNit+NlS/gVFEypabVAqwl5OsmrfYOnocLL3aZFbKGM6OJ7skRCxw3zLm77eppYtag/qNX8akdjiYW4nSXV6d10YALGn7b5f/fKUyDws0RVsboMDmlWbAfqHdrFouhV2rIfUD1MfVZLtRsZkrwwhZUyvXd6WVTrzk+A7KLVyK/libJM3wQIDAQAB"
    refresh-duration-in-seconds: 600
    rotation-duration-before-expire-in-seconds: 300
    access-duration-in-seconds: 120
