spring:
  application:
    name: notification-web-service
  datasource:
    url: jdbc:postgresql://localhost:5432/qlaundry?currentSchema=notif
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      password: '12345'
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@email.com
    password: 'password'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  threads:
    virtual:
      enabled: true

server:
  port: 8102

app:
  mail:
    sender: email@email.com
  notification:
    stream:
      email:
        key: 'notification:email:'
        group: notification-service
        consumer: notification-web-service-1
